configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/treblle%2Ftest-trebllewith-stainless-b8c31fd538edd65da20f40cbe7488b63ab9a7e089699295e8f6eb1224e47cec8.yml
